engines:
  duplication:
    enabled: true
    config:
      languages:
      - bash
      - python
      - perl
  fixme:
    enabled: true
  pep8:
    enabled: true
    checks:
      E501:
        enabled: false
      E302:
        enabled: false
  radon:
    enabled: true
    checks:
      Complexity:
        enabled: false
  shellcheck:
    enabled: true
ratings:
  paths:
  - "**"
exclude_paths: []
