#!/usr/bin/python
"""
-mak
This simply takes the ldif generated by newyear_ldif.py
and builds it into an ldapmodify formatted ldif.

To be used with the ldap modify query below
ldapmodify -x -D cn=root,ou=ldap,o=redbrick -y /etc/ldap.secret -f [LDIF_FROM_THIS_SCRIPT]
"""
import sys

def modify_template(l_uid, l_years_paid, l_newbie, l_reserved):
    """print modify ldif template"""
    if l_uid != '' and l_years_paid != '' and l_reserved is False:
        mod_temp = "dn: uid=" + l_uid.strip() +\
            "\nchangetype: modify\nreplace: yearsPaid\nyearsPaid: " + l_years_paid.strip() + "\n"
        if l_newbie == '1':
            mod_temp += "-\nreplace: newbie\nnewbie: FALSE\n\n"
        else:
            mod_temp += "\n"
        print(mod_temp)

# open ldif
with open(sys.argv[1], 'r') as content:
    LDIF = content.read()
# split by user
GETDN = LDIF.split('dn: uid=')
for i in range(1, len(GETDN)):
    thisdn = GETDN[i].split('\n')
    newbie = 'NONE'
    reserved = False
    # split by users variables
    for j in range(0, len(thisdn)):
        x = thisdn[j].rstrip()
        uid = thisdn[0].rstrip()
        if 'reserved' in uid:
            reserved = True
        try:
            if x.startswith("yearsPaid:"):
                years_paid = str(int(x.split()[1])).strip()
            elif x.startswith("newbie:"):
                newbie = '1'
            else:
                continue
        except IndexError:
            break
    modify_template(uid, years_paid, newbie, reserved)
